# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  
  sudo: false

# Commands to be run before your environment runs.
before_script:
   - curl -s http://getcomposer.org/installer | php
   - php composer.phar install  --dev --no-interaction --prefer-source

# Commands you want to run that will verify your build.
script:  ./vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
