#Definindo a liguagem
language: php

php:
    - 5.5
    - 5.4
    - 5.3
    - 7.0
before_install:
    -php /home/travis/.phpenv/versions/7.0.0/bin/composer.phar self-update
#Instalar dependências
before_script: composer install

#passando o caminho para execução do teste
script: phpunit --configuration test/phpunit.xml

notifications:
    on_success: never
    on_failure: never
