#Definindo a liguagem
language: php

php:
    - 5.5
    - 5.4
    - 5.3
    - 7.0

before_script: composer install

#passando o caminho para execução do teste
script: phpunit --configuration Teste/phpunit.xml

notifications:
    on_success: never
    on_failure: never
